### ISSUE TITLE
Visualize CLT test results in PRs

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/clt#23]
Currently if a CLT test fails it's not visible in the PR, e.g.:
![image](https://github.com/manticoresoftware/clt/assets/28719845/b951649e-6816-4edc-afc8-4eadedc168f7)

Let's improve the action, so we put test results right to the PR for better visibility and faster decision making.

**Comment by donhardman** [comment]
The rest of the board implementation is blocked by the following task: https://github.com/manticoresoftware/manticoresearch-buddy/issues/248.

**Comment by donhardman** [comment]
Implemented and merged in this pull: https://github.com/manticoresoftware/clt/pull/30

**Comment by sanikolaev** [comment]
As discussed, let's try to visualize failed tests hiding them under `<details>`.

**Comment by donhardman** [comment]
The fixes we discussed were implemented in this pull request: https://github.com/manticoresoftware/clt/pull/31
