### ISSUE TITLE
Tests stuck on MacOS

### ISSUE THREAD

**Issue by djklim87** [manticoresoftware/clt#28]

**Comment by djklim87** [comment]
Often I face an issue when the test gets stuck right after the start. REP file of specified test is usually empty this time.

It happens only in MacOS (at Ubuntu all works fine). 
Unfortunately, I can't reproduce this now (just yesterday it happens each 2nd run)

**Comment by djklim87** [comment]
It start happens again (Docker project):

Pre builds steps 
``` 
docker build -t dnd:latest ./clt_tests/testkit/
```

```
RUN_ARGS="-v $(pwd):/docker --privileged" ../clt/clt test -d -t ./clt_tests/tests/plain-indexes-crontab.rec dnd:latest
### It runs normally 


RUN_ARGS="-v $(pwd):/docker --privileged" ../clt/clt test -d -t ./clt_tests/tests/plain-indexes-crontab2.rec dnd:latest
### This run sticks
```

**Comment by donhardman** [comment]
During debugging, I discovered a magic random bytes link inside the container which seems to get stuck on OSX. There doesn't appear to be anything related to CLT, so the issue might just be with the Docker setup inside the container we use for testing or with domain resolving.

I recommend removing the external URL from the Dockerfile and using a different method, as this is also not secure.

![Image](https://github.com/manticoresoftware/clt/assets/59067742/b9608923-d726-464c-91db-163e96e99257)

P.S. It's done after 200s that is just huge delay but nothing wrong in CLT I found: `[+] Building 201.2s (12/24)                                     docker:default`

**Comment by djklim87** [comment]
Unfortunately, the build step in any tes [it's 3th step](https://github.com/manticoresoftware/docker/blob/master/clt_tests/tests/base/init.recb#L13). So in case your test is stuck at that step, your REP file already will be filled by some logs. In my case `rep` file **empty**

**Comment by sanikolaev** [comment]
@djklim87 As discussed, please prepare an example of a hanging test without dind.
