### ISSUE TITLE
Support array in test_prefix

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/clt#32]
In some cases it makes sense to provide multiple entries in `test_prefix` in the CLT action. Let's add support of arrays in `test_prefix`.

**Comment by donhardman** [comment]
I've added support for multiple inputs in test_prefix that should follow this format:

```
test_prefix: test-prefix
```

or 

```
test_prefix: |-
  prefix1 
  prefix2
```

I've also refactored and updated the flow in ManticoreSearch to group and simplify the CLT tests into a matrix: https://github.com/manticoresoftware/manticoresearch/pull/2075

The version 0.1.23 of CLT also has a `comment_mode` parameter that can be set to 'always' or 'failures', defaulting to 'always'.
