### ISSUE TITLE
Add default delay a few ms between inputs

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/clt#43]
Sometimes, when you replay a CLT test, one input may run too soon after the previous one. It is recommended to add a default delay between inputs, such as 5ms.

**Comment by donhardman** [comment]
Implemented in this pull: https://github.com/manticoresoftware/clt/pull/44

**Comment by donhardman** [comment]
We need to review and, if all is good, merge to the main branch and set a new tag with an updated version.

**Comment by donhardman** [comment]
Merged to the main. Version of CLT that supports delay: 0.3.1+
