### ISSUE TITLE
Editor selection support

### ISSUE THREAD

**Issue by djklim87** [manticoresoftware/clt#9]
In CLT we don't have ability to select desired editor

**Comment by donhardman** [comment]
It was implemented and merged into main, `export CLT_EDITOR=nano` to make it work.

**Comment by sanikolaev** [comment]
> It was implemented and merged into main, export CLT_EDITOR=nano to make it work.

Please add this info to the docs.

**Comment by donhardman** [comment]
Added information and updated changes with the usage of CLT action and other fixes: https://github.com/manticoresoftware/clt/commit/e03a316a9cef1f3e350ed30376bd73eac9d605c3
